name: Parimg
model_type: RealESRGANModel
scale: 2
num_gpu: auto
manual_seed: 0

l1_gt_usm: False 
percep_gt_usm: False 
gan_gt_usm: False

high_order_degradation: False

datasets:
  train:
    name: Image Pairs
    type: PairedImageDataset
    dataroot_gt: /media/phips/One Touch/Upscale/TrainDataset/GoodQuality/ImagePairs-Training/hr/
    dataroot_lq: /media/phips/One Touch/Upscale/TrainDataset/GoodQuality/ImagePairs-Training/lr/
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: True
    use_rot: True

    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: validation
    type: PairedImageDataset
    dataroot_gt: /media/phips/One Touch/Upscale/TrainDataset/GoodQuality/ImagePairs-Training/val/hr/
    dataroot_lq: /media/phips/One Touch/Upscale/TrainDataset/GoodQuality/ImagePairs-Training/val/lr/
    io_backend:
      type: disk

network_g:  
  type: SRVGGNetCompact
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_conv: 16
  upscale: 2
  act_type: prelu

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  skip_connection: True

path:
  pretrain_network_g: experiments/pretrained_models/2x_Compact_Pretrain.pth
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: ~
  param_key_d: params
  strict_load_d: true
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [400000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1

  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  net_d_iters: 1
  net_d_init_iters: 0


val:
  val_freq: 1000
  save_img: True

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false      

logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500