# GENERATE TIME: Mon Jun 19 00:03:10 2023
# CMD:
# train.py -opt options/train/OmniSR/2xHFA2kAVCOmniSR_Sharp.yml

name: 2xHFA2kAVCOmniSR_Sharp
model_type: OmniSRGANModel
scale: 2
num_gpu: 1
manual_seed: 0

l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: True
gt_usm: False
high_order_degradation : False
try_autoamp_g: False
try_autoamp_d: False

datasets:
  train:
    name: HFA2k_LUDVAE
    type: PairedImageDataset
    dataroot_gt: /home/phips/Documents/datasets/HFA2k
    dataroot_lq: /home/phips/Documents/datasets/HFA2k_h264
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true
    use_shuffle: True
    
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: validation
    type: PairedImageDataset
    dataroot_gt: /home/phips/Documents/datasets/HFA2kvalHR_half
    dataroot_lq: /home/phips/Documents/datasets/HFA2kvalLRh264_half
    io_backend:
      type: disk

network_g:
  type: OmniSRNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  upsampling: 2
  res_num: 5
  block_num: 1
  bias: True
  block_script_name: OSA
  block_class_name: OSA_Block
  window_size: 8
  pe: True
  ffn_bias: True
  
#network_d:
#  type: UNetDiscriminatorSN
#  num_in_ch: 3
#  num_feat: 64
#  #skip_connection: True
  
network_d:
  type: multiscale
  num_in_ch: 3
  num_feat: 64
  num_D: 2

path:
  pretrain_network_g: /home/phips/Documents/traiNNer-redux-FJ/experiments/pretrained_models/2xHFA2kAVCOmniSR.pth
  strict_load_g: true
  param_key_g: params_ema
  pretrain_network_d:
  strict_load_d: true
  param_key_d: params_ema
  resume_state:


train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 1.5e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [400000]
    gamma: 0.5

  total_iter: 1600000
  warmup_iter: -1

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      "conv1_2": 0.1
      "conv2_2": 0.1
      "conv3_4": 1
      "conv4_4": 1
      "conv5_4": 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1
  contextual_opt:
    type: ContextualLoss
    loss_weight: 0.5
    layer_weights:
      "conv_3_2": 1
      "conv_4_2": 1
    max_1d_size: 64
    distance_type: "cosine"
    calc_type: "regular"
    z_norm: false
    crop_quarter: false,
    b: 1.0
    band_width: 0.5
    use_vgg: true,
    net: vgg19
  color_opt:
    type: ColorLoss
    criterion: "l1"
    loss_weight: 1.0
  avg_opt:
    type: AverageLoss
    criterion: "l1"
    loss_weight: 1.0
    scale: 2
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

val:
  val_freq: 1000
  save_img: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
